-- Disciplinary Incident Tracker — historical rows from the spreadsheet Sagaree keeps.
-- Blanks preserved. Dates kept as text in *_raw as well as parsed, so an
-- unreadable or contradictory date is visible and correctable rather than
-- silently wrong. Idempotent on (name + received-on text + action).

insert into hr_tracker_records (kind,employee_code,employee_name,role_title,location,manager,event_date,event_date_raw,investigation_end,investigation_raw,findings,action_taken,bonus,filed_by,final_comments,source)
select 'disciplinary',null,'Tyler-Jane Fynn','NT','Fourways','Nontethelelo Nxumalo',date '2026-01-08','08 Jan 26',date '2026-01-08','08 January 2026','First written warning for Failure to Comply with Company Policy','First written warning','50% Bonus','Sagaree','Warning Letter Issued','seed'
where not exists (select 1 from hr_tracker_records where kind='disciplinary' and employee_name='Tyler-Jane Fynn' and coalesce(event_date_raw,'')='08 Jan 26' and coalesce(action_taken,'')=coalesce('First written warning',''));
insert into hr_tracker_records (kind,employee_code,employee_name,role_title,location,manager,event_date,event_date_raw,investigation_end,investigation_raw,findings,action_taken,bonus,filed_by,final_comments,source)
select 'disciplinary',null,'Flora Nzamba','NT','Seapoint','Simamkele Mfene',date '2026-01-09','9 Jan 26',date '2026-01-09','9 January 2026','Complaint from client','Final Written warning','No Bonus','Sagaree','Disciplinary Hearing - Final Written Warning','seed'
where not exists (select 1 from hr_tracker_records where kind='disciplinary' and employee_name='Flora Nzamba' and coalesce(event_date_raw,'')='9 Jan 26' and coalesce(action_taken,'')=coalesce('Final Written warning',''));
insert into hr_tracker_records (kind,employee_code,employee_name,role_title,location,manager,event_date,event_date_raw,investigation_end,investigation_raw,findings,action_taken,bonus,filed_by,final_comments,source)
select 'disciplinary',null,'Beverly Shange','NT','Ballito','Kiveshni Govender',date '2026-01-13','13 Jan 26',date '2026-01-13','13 January 2026','Disciplinary Hearing was Held. Final written warning was sent out. And was signed by Beverly Shange','Final Written Warning','No Bonus','Sagaree','Disciplinary Hearing - Final Written Warning','seed'
where not exists (select 1 from hr_tracker_records where kind='disciplinary' and employee_name='Beverly Shange' and coalesce(event_date_raw,'')='13 Jan 26' and coalesce(action_taken,'')=coalesce('Final Written Warning',''));
insert into hr_tracker_records (kind,employee_code,employee_name,role_title,location,manager,event_date,event_date_raw,investigation_end,investigation_raw,findings,action_taken,bonus,filed_by,final_comments,source)
select 'disciplinary',null,'Zandiswa Mqikela','NT','Claremont','Rene Brown',date '2026-01-15','15 Jan 26',date '2026-02-03','3 February 2026','First Written Warning','First written warning','No Bonus','Sagaree',null,'seed'
where not exists (select 1 from hr_tracker_records where kind='disciplinary' and employee_name='Zandiswa Mqikela' and coalesce(event_date_raw,'')='15 Jan 26' and coalesce(action_taken,'')=coalesce('First written warning',''));
insert into hr_tracker_records (kind,employee_code,employee_name,role_title,location,manager,event_date,event_date_raw,investigation_end,investigation_raw,findings,action_taken,bonus,filed_by,final_comments,source)
select 'disciplinary',null,'Tariro Muchabaye','NT','Tablebay','Bandlakazi Carol',date '2026-01-16','16 Jan 26',date '2026-01-16','16 January 2026','First written warning for Lateness','First Written warning','50% Bonus','Sagaree','Warning Letter Issued','seed'
where not exists (select 1 from hr_tracker_records where kind='disciplinary' and employee_name='Tariro Muchabaye' and coalesce(event_date_raw,'')='16 Jan 26' and coalesce(action_taken,'')=coalesce('First Written warning',''));
insert into hr_tracker_records (kind,employee_code,employee_name,role_title,location,manager,event_date,event_date_raw,investigation_end,investigation_raw,findings,action_taken,bonus,filed_by,final_comments,source)
select 'disciplinary',null,'Julian Mcina','SM','Fourways','Nontethelelo Nxumalo',date '2026-01-16','16 Jan 26',date '2026-01-16','16 January 2026','First written warning for Lateness','First Written warning','50% Bonus','Sagaree','Warning Letter Issued','seed'
where not exists (select 1 from hr_tracker_records where kind='disciplinary' and employee_name='Julian Mcina' and coalesce(event_date_raw,'')='16 Jan 26' and coalesce(action_taken,'')=coalesce('First Written warning',''));
insert into hr_tracker_records (kind,employee_code,employee_name,role_title,location,manager,event_date,event_date_raw,investigation_end,investigation_raw,findings,action_taken,bonus,filed_by,final_comments,source)
select 'disciplinary',null,'Shenaaz Kuvashi','SM','Kloof','Chante Harrison',date '2026-01-18','18 Jan 26',null,'TBC','Under Investigation','TBC','No Bonus','Sagaree','Warning Letter Issued','seed'
where not exists (select 1 from hr_tracker_records where kind='disciplinary' and employee_name='Shenaaz Kuvashi' and coalesce(event_date_raw,'')='18 Jan 26' and coalesce(action_taken,'')=coalesce('TBC',''));
insert into hr_tracker_records (kind,employee_code,employee_name,role_title,location,manager,event_date,event_date_raw,investigation_end,investigation_raw,findings,action_taken,bonus,filed_by,final_comments,source)
select 'disciplinary',null,'Rushda Cottle','SM','Riverlands','Farieda',date '2026-01-20','20 Jan 26',date '2026-01-20','20 January 2026','Notice of Hearing - For absconding - Dismissed','Dismissed','No Bonus','Sagaree','Disciplinary Hearing - Dismissed','seed'
where not exists (select 1 from hr_tracker_records where kind='disciplinary' and employee_name='Rushda Cottle' and coalesce(event_date_raw,'')='20 Jan 26' and coalesce(action_taken,'')=coalesce('Dismissed',''));
insert into hr_tracker_records (kind,employee_code,employee_name,role_title,location,manager,event_date,event_date_raw,investigation_end,investigation_raw,findings,action_taken,bonus,filed_by,final_comments,source)
select 'disciplinary',null,'Shenaz Kuvashi','AM','Seapoint','Zikhona',date '2026-01-20','20 Jan 26',null,'Meet with HR','Shenaz and Aqilah was asked to speak regarding the incident. It was decided that the incidnet will be investigated and CCTV footage will be checked.','Under Investigation','TBC','TBC','TBC','seed'
where not exists (select 1 from hr_tracker_records where kind='disciplinary' and employee_name='Shenaz Kuvashi' and coalesce(event_date_raw,'')='20 Jan 26' and coalesce(action_taken,'')=coalesce('Under Investigation',''));
insert into hr_tracker_records (kind,employee_code,employee_name,role_title,location,manager,event_date,event_date_raw,investigation_end,investigation_raw,findings,action_taken,bonus,filed_by,final_comments,source)
select 'disciplinary',null,'Nonhlanhla Mathebula','NT','Mall of South','Tshepiso Sithole',date '2026-01-20','20 Jan 26',date '2026-01-20','20 Januart 2026','First written Warning -Lateness','First Written warning','50% Bonus','Sagaree','Warning Letter Issued','seed'
where not exists (select 1 from hr_tracker_records where kind='disciplinary' and employee_name='Nonhlanhla Mathebula' and coalesce(event_date_raw,'')='20 Jan 26' and coalesce(action_taken,'')=coalesce('First Written warning',''));
insert into hr_tracker_records (kind,employee_code,employee_name,role_title,location,manager,event_date,event_date_raw,investigation_end,investigation_raw,findings,action_taken,bonus,filed_by,final_comments,source)
select 'disciplinary',null,'Charmaine Dube','NT','Fourways','Julian Mchina',date '2026-01-20','20 Jan 26',date '2026-01-26','26 January 2026','First written Warning Lateness','First Written warning','50% Bonus','Sagaree','Warning Letter Issued','seed'
where not exists (select 1 from hr_tracker_records where kind='disciplinary' and employee_name='Charmaine Dube' and coalesce(event_date_raw,'')='20 Jan 26' and coalesce(action_taken,'')=coalesce('First Written warning',''));
insert into hr_tracker_records (kind,employee_code,employee_name,role_title,location,manager,event_date,event_date_raw,investigation_end,investigation_raw,findings,action_taken,bonus,filed_by,final_comments,source)
select 'disciplinary',null,'Tadiwanashe Chiyangwa','AM','Kuilsrivier','Thina',date '2026-01-20','20 Jan 26',date '2026-01-29','29 January 2026','Disciplinary Hearing','Dismissed','No Bonus','Sagaree','Termination Letter Sent','seed'
where not exists (select 1 from hr_tracker_records where kind='disciplinary' and employee_name='Tadiwanashe Chiyangwa' and coalesce(event_date_raw,'')='20 Jan 26' and coalesce(action_taken,'')=coalesce('Dismissed',''));
insert into hr_tracker_records (kind,employee_code,employee_name,role_title,location,manager,event_date,event_date_raw,investigation_end,investigation_raw,findings,action_taken,bonus,filed_by,final_comments,source)
select 'disciplinary',null,'Zanele Malwane','NT','Eastgate','Elizabeth Malebane',date '2026-01-22','22 Jan 26',date '2026-01-23','23 January 2026','First Written Warning','First Written warning','50% Bonus','Sagaree','Warning Letter Issued','seed'
where not exists (select 1 from hr_tracker_records where kind='disciplinary' and employee_name='Zanele Malwane' and coalesce(event_date_raw,'')='22 Jan 26' and coalesce(action_taken,'')=coalesce('First Written warning',''));
insert into hr_tracker_records (kind,employee_code,employee_name,role_title,location,manager,event_date,event_date_raw,investigation_end,investigation_raw,findings,action_taken,bonus,filed_by,final_comments,source)
select 'disciplinary',null,'Linda Dosi',null,'Bree','Fazlin Francis',date '2026-01-22','22 Jan 26',date '2026-01-26','26 January 2026','First Written Warning','First Written warning','50% Bonus','Sagaree','Warning Letter Issued','seed'
where not exists (select 1 from hr_tracker_records where kind='disciplinary' and employee_name='Linda Dosi' and coalesce(event_date_raw,'')='22 Jan 26' and coalesce(action_taken,'')=coalesce('First Written warning',''));
insert into hr_tracker_records (kind,employee_code,employee_name,role_title,location,manager,event_date,event_date_raw,investigation_end,investigation_raw,findings,action_taken,bonus,filed_by,final_comments,source)
select 'disciplinary',null,'Halicia Siwan Smith','AM','Plumstead','Isabelle Klusenar',date '2026-01-22','22 Jan 26',date '2026-01-29','29 January 2026','Disciplinary Hearing','Dismissed','No Bonus','Sagaree','Termination Letter Sent','seed'
where not exists (select 1 from hr_tracker_records where kind='disciplinary' and employee_name='Halicia Siwan Smith' and coalesce(event_date_raw,'')='22 Jan 26' and coalesce(action_taken,'')=coalesce('Dismissed',''));
insert into hr_tracker_records (kind,employee_code,employee_name,role_title,location,manager,event_date,event_date_raw,investigation_end,investigation_raw,findings,action_taken,bonus,filed_by,final_comments,source)
select 'disciplinary',null,'Mishca Johannes','AM','Sandown','Fahiema VD Schyff',date '2026-01-24','24 Jan 26',date '2026-02-03','3 February 2026','First Written Warning','First Written warning','50% Bonus','Sagaree','Warning Letter Issued','seed'
where not exists (select 1 from hr_tracker_records where kind='disciplinary' and employee_name='Mishca Johannes' and coalesce(event_date_raw,'')='24 Jan 26' and coalesce(action_taken,'')=coalesce('First Written warning',''));
insert into hr_tracker_records (kind,employee_code,employee_name,role_title,location,manager,event_date,event_date_raw,investigation_end,investigation_raw,findings,action_taken,bonus,filed_by,final_comments,source)
select 'disciplinary',null,'Miche Cloete','AM','Bree','Fazlin Francis',date '2026-01-26','26 Jan 26',date '2026-01-29','29 January 2026','Disciplinary Hearing','Final Written Warning','No Bonus','Sagaree','Final Written Warning Issued','seed'
where not exists (select 1 from hr_tracker_records where kind='disciplinary' and employee_name='Miche Cloete' and coalesce(event_date_raw,'')='26 Jan 26' and coalesce(action_taken,'')=coalesce('Final Written Warning',''));
insert into hr_tracker_records (kind,employee_code,employee_name,role_title,location,manager,event_date,event_date_raw,investigation_end,investigation_raw,findings,action_taken,bonus,filed_by,final_comments,source)
select 'disciplinary',null,'Tara-lee Bam','AM','Westlake','Sineyethu Ngcelwana',date '2026-01-27','27 Jan 26',date '2026-01-28','28 January 2026','First Written Warning','First Written warning','50% Bonus','Sagaree','Warning Letter Issued','seed'
where not exists (select 1 from hr_tracker_records where kind='disciplinary' and employee_name='Tara-lee Bam' and coalesce(event_date_raw,'')='27 Jan 26' and coalesce(action_taken,'')=coalesce('First Written warning',''));
insert into hr_tracker_records (kind,employee_code,employee_name,role_title,location,manager,event_date,event_date_raw,investigation_end,investigation_raw,findings,action_taken,bonus,filed_by,final_comments,source)
select 'disciplinary',null,'Tarryn Arendse','AM','Seapoint','Farieda Jackson',date '2026-01-29','29 Jan 26',date '2026-02-03','03 February 2026','First Written Warning','First Written warning','50% Bonus','Sagaree','Warning Letter Issued','seed'
where not exists (select 1 from hr_tracker_records where kind='disciplinary' and employee_name='Tarryn Arendse' and coalesce(event_date_raw,'')='29 Jan 26' and coalesce(action_taken,'')=coalesce('First Written warning',''));
insert into hr_tracker_records (kind,employee_code,employee_name,role_title,location,manager,event_date,event_date_raw,investigation_end,investigation_raw,findings,action_taken,bonus,filed_by,final_comments,source)
select 'disciplinary',null,'Makhethe Rasekoai','AM','Eastgate','Andile Sisilana',date '2026-02-06','6 Feb 26',date '2026-01-22','22 January 2026','Disciplinary Hearing happened 06/02/26 - Makhethe was Dismissed from 06/02/26','Dismissed','No Bonus','Sagaree','Termination Letter Issued','seed'
where not exists (select 1 from hr_tracker_records where kind='disciplinary' and employee_name='Makhethe Rasekoai' and coalesce(event_date_raw,'')='6 Feb 26' and coalesce(action_taken,'')=coalesce('Dismissed',''));
insert into hr_tracker_records (kind,employee_code,employee_name,role_title,location,manager,event_date,event_date_raw,investigation_end,investigation_raw,findings,action_taken,bonus,filed_by,final_comments,source)
select 'disciplinary','B223-M','Tara-Lee Bam','AM','Westlake','Farieda',date '2026-02-18','18 Feb 26',date '2026-03-03','3 March 26','Second Written Warning','Second Written Warning','50% Bonus','Sagaree','Warning Letter sent','seed'
where not exists (select 1 from hr_tracker_records where kind='disciplinary' and employee_name='Tara-Lee Bam' and coalesce(event_date_raw,'')='18 Feb 26' and coalesce(action_taken,'')=coalesce('Second Written Warning',''));
insert into hr_tracker_records (kind,employee_code,employee_name,role_title,location,manager,event_date,event_date_raw,investigation_end,investigation_raw,findings,action_taken,bonus,filed_by,final_comments,source)
select 'disciplinary',null,'Akeela Mazhanda','NT','Seapoint','Zikhona Qelewa',date '2026-02-19','19 Feb 26',date '2026-01-28','28 January 2026','Disciplinary Hearing rescheuled 19 February','Dismissed','No Bonus','Sagaree','Termination Letter Issued','seed'
where not exists (select 1 from hr_tracker_records where kind='disciplinary' and employee_name='Akeela Mazhanda' and coalesce(event_date_raw,'')='19 Feb 26' and coalesce(action_taken,'')=coalesce('Dismissed',''));
insert into hr_tracker_records (kind,employee_code,employee_name,role_title,location,manager,event_date,event_date_raw,investigation_end,investigation_raw,findings,action_taken,bonus,filed_by,final_comments,source)
select 'disciplinary','B580','Snodia Svileiro','NT','Greenpoint','Nqabisa Mpupa',date '2026-02-20','20 Feb 26',date '2026-02-20','20 February 26','Second Written Warning','Second Written Warning','50% Bonus','Sagaree','Warning Sent','seed'
where not exists (select 1 from hr_tracker_records where kind='disciplinary' and employee_name='Snodia Svileiro' and coalesce(event_date_raw,'')='20 Feb 26' and coalesce(action_taken,'')=coalesce('Second Written Warning',''));
insert into hr_tracker_records (kind,employee_code,employee_name,role_title,location,manager,event_date,event_date_raw,investigation_end,investigation_raw,findings,action_taken,bonus,filed_by,final_comments,source)
select 'disciplinary','B459','Vanessa Dlamini','NT','Sandown','Fahiema VD Schyff',date '2026-02-23','23 Feb 26',date '2026-02-23','23 February 26','First Written Warning','First Written Warning','50% Bonus','Sagaree','Warning Letter sent','seed'
where not exists (select 1 from hr_tracker_records where kind='disciplinary' and employee_name='Vanessa Dlamini' and coalesce(event_date_raw,'')='23 Feb 26' and coalesce(action_taken,'')=coalesce('First Written Warning',''));
insert into hr_tracker_records (kind,employee_code,employee_name,role_title,location,manager,event_date,event_date_raw,investigation_end,investigation_raw,findings,action_taken,bonus,filed_by,final_comments,source)
select 'disciplinary','B231','Omega Kafume','NT','Sandown','Fahiema VD Schyuff',date '2026-02-26','26 Feb 26',date '2026-03-03','3 March 26','First Written Warning','First Written Warning','50% Bonus','Sagaree','Warning Letter sent','seed'
where not exists (select 1 from hr_tracker_records where kind='disciplinary' and employee_name='Omega Kafume' and coalesce(event_date_raw,'')='26 Feb 26' and coalesce(action_taken,'')=coalesce('First Written Warning',''));
insert into hr_tracker_records (kind,employee_code,employee_name,role_title,location,manager,event_date,event_date_raw,investigation_end,investigation_raw,findings,action_taken,bonus,filed_by,final_comments,source)
select 'disciplinary','B500','Vimbai Chachoka','NT','Tablebay','Julie Adams',date '2026-02-28','28 Feb 26',date '2026-03-03','3 March 26','First Written Warning','First Written Warning','50% Bonus','Sagaree','Warning Letter sent','seed'
where not exists (select 1 from hr_tracker_records where kind='disciplinary' and employee_name='Vimbai Chachoka' and coalesce(event_date_raw,'')='28 Feb 26' and coalesce(action_taken,'')=coalesce('First Written Warning',''));
insert into hr_tracker_records (kind,employee_code,employee_name,role_title,location,manager,event_date,event_date_raw,investigation_end,investigation_raw,findings,action_taken,bonus,filed_by,final_comments,source)
select 'disciplinary','B794','Nothani Sibanda','NT','Mushroom Farm','Nontethelelo Cebile Nxumalo',date '2026-03-02','02 Mar 26',date '2026-03-02','2 March 26','Disciplinary Hearing Scheduled 02 March 2026','Dismissed','No Bonus','Sagaree','Termination Letter Issued','seed'
where not exists (select 1 from hr_tracker_records where kind='disciplinary' and employee_name='Nothani Sibanda' and coalesce(event_date_raw,'')='02 Mar 26' and coalesce(action_taken,'')=coalesce('Dismissed',''));
insert into hr_tracker_records (kind,employee_code,employee_name,role_title,location,manager,event_date,event_date_raw,investigation_end,investigation_raw,findings,action_taken,bonus,filed_by,final_comments,source)
select 'disciplinary','B127','Connie Mdongwe','NT','Claremont','Yasmina',date '2026-03-09','09 Mar 26',date '2026-03-09','09 March 26','First Written Warning','First Written Warning','50% Bonus','Sagaree','Warning Letter sent','seed'
where not exists (select 1 from hr_tracker_records where kind='disciplinary' and employee_name='Connie Mdongwe' and coalesce(event_date_raw,'')='09 Mar 26' and coalesce(action_taken,'')=coalesce('First Written Warning',''));
insert into hr_tracker_records (kind,employee_code,employee_name,role_title,location,manager,event_date,event_date_raw,investigation_end,investigation_raw,findings,action_taken,bonus,filed_by,final_comments,source)
select 'disciplinary','B266','Thina Mene','NT','Claremont','Rene Brown',date '2026-03-11','11 Mar 26',date '2026-03-11','11 March 26','First Written Warning','First Written Warning','50% Bonus','Sagaree','Warning Letter sent','seed'
where not exists (select 1 from hr_tracker_records where kind='disciplinary' and employee_name='Thina Mene' and coalesce(event_date_raw,'')='11 Mar 26' and coalesce(action_taken,'')=coalesce('First Written Warning',''));
insert into hr_tracker_records (kind,employee_code,employee_name,role_title,location,manager,event_date,event_date_raw,investigation_end,investigation_raw,findings,action_taken,bonus,filed_by,final_comments,source)
select 'disciplinary','B691','Ntombi Thawuse','NT','Claremont','Rene Brown',date '2026-03-11','11 Mar 26',date '2026-03-11','11 March 26','First Written Warning','First Written Warning','50% Bonus','Sagaree','Warning Letter sent','seed'
where not exists (select 1 from hr_tracker_records where kind='disciplinary' and employee_name='Ntombi Thawuse' and coalesce(event_date_raw,'')='11 Mar 26' and coalesce(action_taken,'')=coalesce('First Written Warning',''));
insert into hr_tracker_records (kind,employee_code,employee_name,role_title,location,manager,event_date,event_date_raw,investigation_end,investigation_raw,findings,action_taken,bonus,filed_by,final_comments,source)
select 'disciplinary','B282','Nwabisa Mvumu','NT','Claremont','Rene Brown',date '2026-03-11','11 Mar 26',date '2026-03-11','11 March 26','First Written Warning','First Written Warning','50% Bonus','Sagaree','Warning Letter sent','seed'
where not exists (select 1 from hr_tracker_records where kind='disciplinary' and employee_name='Nwabisa Mvumu' and coalesce(event_date_raw,'')='11 Mar 26' and coalesce(action_taken,'')=coalesce('First Written Warning',''));
insert into hr_tracker_records (kind,employee_code,employee_name,role_title,location,manager,event_date,event_date_raw,investigation_end,investigation_raw,findings,action_taken,bonus,filed_by,final_comments,source)
select 'disciplinary','B832-W','Austen Klaas','Driver','BOA H/O','Elton Barnes',date '2026-03-19','19 Mar 26',date '2026-03-19','19 March 26','Disciplinary Hearing Scheduled 19 March 2026','Dismissed','No Bonus','Sagaree','Termination Letter Issued','seed'
where not exists (select 1 from hr_tracker_records where kind='disciplinary' and employee_name='Austen Klaas' and coalesce(event_date_raw,'')='19 Mar 26' and coalesce(action_taken,'')=coalesce('Dismissed',''));
insert into hr_tracker_records (kind,employee_code,employee_name,role_title,location,manager,event_date,event_date_raw,investigation_end,investigation_raw,findings,action_taken,bonus,filed_by,final_comments,source)
select 'disciplinary','B437','Dunyiswa Ngcoza','NT','Claremont','Rene Brown',date '2026-03-19','19 Mar 26',date '2026-03-19','19 March 2026','Final Written Warning','Final Written Warning','No Bonus','Sagaree','Warning Letter Signed','seed'
where not exists (select 1 from hr_tracker_records where kind='disciplinary' and employee_name='Dunyiswa Ngcoza' and coalesce(event_date_raw,'')='19 Mar 26' and coalesce(action_taken,'')=coalesce('Final Written Warning',''));
insert into hr_tracker_records (kind,employee_code,employee_name,role_title,location,manager,event_date,event_date_raw,investigation_end,investigation_raw,findings,action_taken,bonus,filed_by,final_comments,source)
select 'disciplinary','B105','Philiswa Mbambisa','NT','Claremont','Rene Brown',date '2026-03-20','20 Mar 26',date '2026-03-19','19 March 2026','Final Written Warning','Final Written Warning','No Bonus','Sagaree','Warning Letter Signed','seed'
where not exists (select 1 from hr_tracker_records where kind='disciplinary' and employee_name='Philiswa Mbambisa' and coalesce(event_date_raw,'')='20 Mar 26' and coalesce(action_taken,'')=coalesce('Final Written Warning',''));
insert into hr_tracker_records (kind,employee_code,employee_name,role_title,location,manager,event_date,event_date_raw,investigation_end,investigation_raw,findings,action_taken,bonus,filed_by,final_comments,source)
select 'disciplinary',null,'Kane Mkosana','VIB-Barista','VIB Cafe','Maree Young',null,'23 Mar',null,'23 March','First Written Warning','First Written Warning','50% Bonus','Sagaree','Warning Letter Signed','seed'
where not exists (select 1 from hr_tracker_records where kind='disciplinary' and employee_name='Kane Mkosana' and coalesce(event_date_raw,'')='23 Mar' and coalesce(action_taken,'')=coalesce('First Written Warning',''));
insert into hr_tracker_records (kind,employee_code,employee_name,role_title,location,manager,event_date,event_date_raw,investigation_end,investigation_raw,findings,action_taken,bonus,filed_by,final_comments,source)
select 'disciplinary','B823-M','Noxolo Zikhali','AM','Eastgate','Elizabeth Malebane',date '2026-03-03','03 Mar 26',date '2026-03-03','03 March 2026','Final Written Warning','Final Written Warning','No Bonus','Sagaree','Final Written Warning Issued','seed'
where not exists (select 1 from hr_tracker_records where kind='disciplinary' and employee_name='Noxolo Zikhali' and coalesce(event_date_raw,'')='03 Mar 26' and coalesce(action_taken,'')=coalesce('Final Written Warning',''));
insert into hr_tracker_records (kind,employee_code,employee_name,role_title,location,manager,event_date,event_date_raw,investigation_end,investigation_raw,findings,action_taken,bonus,filed_by,final_comments,source)
select 'disciplinary','B223-M','Tara-Lee Bam','AM','Westlake','Farieda',date '2026-03-12','12 Mar 26',date '2026-03-12','12 March 2026','Final Written Warning','Final Written Warning','No Bonus','Sagaree','Final Written Warning Issued','seed'
where not exists (select 1 from hr_tracker_records where kind='disciplinary' and employee_name='Tara-Lee Bam' and coalesce(event_date_raw,'')='12 Mar 26' and coalesce(action_taken,'')=coalesce('Final Written Warning',''));
insert into hr_tracker_records (kind,employee_code,employee_name,role_title,location,manager,event_date,event_date_raw,investigation_end,investigation_raw,findings,action_taken,bonus,filed_by,final_comments,source)
select 'disciplinary','B266','Thina Mene','NT','Claremont','Rene Brown',date '2026-03-13','13 Mar 26',date '2026-03-13','13 March 2026','First Written Warning','First Written Warning','50% Bonus','Sagaree','Warning Letter Signed','seed'
where not exists (select 1 from hr_tracker_records where kind='disciplinary' and employee_name='Thina Mene' and coalesce(event_date_raw,'')='13 Mar 26' and coalesce(action_taken,'')=coalesce('First Written Warning',''));
insert into hr_tracker_records (kind,employee_code,employee_name,role_title,location,manager,event_date,event_date_raw,investigation_end,investigation_raw,findings,action_taken,bonus,filed_by,final_comments,source)
select 'disciplinary','B712','Lesego Boitumelo Mahlase','NT','Mall of SOuth','Tshepiso Sithole',date '2026-03-18','18 Mar 26',date '2026-03-23','23 March 2026','Final Written Warning NOT SIGNED WAITING ON MEETING','Final Written Warning','No Bonus','Sagaree','Final Warning Letter Signed','seed'
where not exists (select 1 from hr_tracker_records where kind='disciplinary' and employee_name='Lesego Boitumelo Mahlase' and coalesce(event_date_raw,'')='18 Mar 26' and coalesce(action_taken,'')=coalesce('Final Written Warning',''));
insert into hr_tracker_records (kind,employee_code,employee_name,role_title,location,manager,event_date,event_date_raw,investigation_end,investigation_raw,findings,action_taken,bonus,filed_by,final_comments,source)
select 'disciplinary','B270-W','Portia Qamingwana','Admin','Warehouse','Elton Barnes',date '2026-03-26','26 Mar 26',date '2026-03-26','26 March 2026','First Written Warning','First Written Warning','50% Bonus','Sagaree','First Written Warning','seed'
where not exists (select 1 from hr_tracker_records where kind='disciplinary' and employee_name='Portia Qamingwana' and coalesce(event_date_raw,'')='26 Mar 26' and coalesce(action_taken,'')=coalesce('First Written Warning',''));
insert into hr_tracker_records (kind,employee_code,employee_name,role_title,location,manager,event_date,event_date_raw,investigation_end,investigation_raw,findings,action_taken,bonus,filed_by,final_comments,source)
select 'disciplinary','B814-M','Chloe Hanekom','Sales','Head Office','Kelly Nel',date '2026-03-27','27 Mar 26',date '2026-03-27','27 March 2026','Meeting with HR','Meeting with HR','n/a','Sagaree','Verbal Warning','seed'
where not exists (select 1 from hr_tracker_records where kind='disciplinary' and employee_name='Chloe Hanekom' and coalesce(event_date_raw,'')='27 Mar 26' and coalesce(action_taken,'')=coalesce('Meeting with HR',''));
insert into hr_tracker_records (kind,employee_code,employee_name,role_title,location,manager,event_date,event_date_raw,investigation_end,investigation_raw,findings,action_taken,bonus,filed_by,final_comments,source)
select 'disciplinary','B782-M','Robin Pharo','AM','Seapoint','Farieda',date '2026-04-09','09 Apr 26',date '2026-04-09','09 April 2026','Disciplinary Meeting with HR','Meeting with HR','50% Bonus','Sagaree','First Written Warning','seed'
where not exists (select 1 from hr_tracker_records where kind='disciplinary' and employee_name='Robin Pharo' and coalesce(event_date_raw,'')='09 Apr 26' and coalesce(action_taken,'')=coalesce('Meeting with HR',''));
insert into hr_tracker_records (kind,employee_code,employee_name,role_title,location,manager,event_date,event_date_raw,investigation_end,investigation_raw,findings,action_taken,bonus,filed_by,final_comments,source)
select 'disciplinary','B682','Felicity Dita','NT','Tablebay','Carol',date '2026-04-09','09 Apr 26',date '2026-04-09','09 April 2026','Meeting with HR','Meeting with HR','n/a','Sagaree','Meet with HR for Clarity with SM','seed'
where not exists (select 1 from hr_tracker_records where kind='disciplinary' and employee_name='Felicity Dita' and coalesce(event_date_raw,'')='09 Apr 26' and coalesce(action_taken,'')=coalesce('Meeting with HR',''));
insert into hr_tracker_records (kind,employee_code,employee_name,role_title,location,manager,event_date,event_date_raw,investigation_end,investigation_raw,findings,action_taken,bonus,filed_by,final_comments,source)
select 'disciplinary','B670','Elisafelo Magadzire','NT','Kuilsrivier','Zandile Khumalo',date '2026-04-13','13 April 26',null,'13 April','First Written Warning','First Written Warning','50% Bonus','Sagaree','First Written Warning','seed'
where not exists (select 1 from hr_tracker_records where kind='disciplinary' and employee_name='Elisafelo Magadzire' and coalesce(event_date_raw,'')='13 April 26' and coalesce(action_taken,'')=coalesce('First Written Warning',''));
insert into hr_tracker_records (kind,employee_code,employee_name,role_title,location,manager,event_date,event_date_raw,investigation_end,investigation_raw,findings,action_taken,bonus,filed_by,final_comments,source)
select 'disciplinary','B257-W','Elton Barnes','WM','BOA H/O','Aniesa Samuels',date '2026-04-15','15 April 26',null,'15 April','Meeting with HR - Clarity over Incident','Meeting with HR','n/a','Sagaree','Meet with HR for Clarity with Warehouse Manager','seed'
where not exists (select 1 from hr_tracker_records where kind='disciplinary' and employee_name='Elton Barnes' and coalesce(event_date_raw,'')='15 April 26' and coalesce(action_taken,'')=coalesce('Meeting with HR',''));
insert into hr_tracker_records (kind,employee_code,employee_name,role_title,location,manager,event_date,event_date_raw,investigation_end,investigation_raw,findings,action_taken,bonus,filed_by,final_comments,source)
select 'disciplinary','B437','Duniswa Ngcoza','NT','Claremont','Farieda',date '2026-04-16','16 April 26',date '2026-04-16','16 April 2026','Final Written Warning','Final Written Warning','No Bonus','Sagaree','Final Written Warning - RESIGNED','seed'
where not exists (select 1 from hr_tracker_records where kind='disciplinary' and employee_name='Duniswa Ngcoza' and coalesce(event_date_raw,'')='16 April 26' and coalesce(action_taken,'')=coalesce('Final Written Warning',''));
insert into hr_tracker_records (kind,employee_code,employee_name,role_title,location,manager,event_date,event_date_raw,investigation_end,investigation_raw,findings,action_taken,bonus,filed_by,final_comments,source)
select 'disciplinary','B157','Peace Munetsi','NT','Westlake','Stacy Buyst',date '2026-04-16','16 April 26',date '2026-04-16','16 April 2026','Final Written Warning','Final Written Warning','No Bonus','Sagaree','Final Written Warning','seed'
where not exists (select 1 from hr_tracker_records where kind='disciplinary' and employee_name='Peace Munetsi' and coalesce(event_date_raw,'')='16 April 26' and coalesce(action_taken,'')=coalesce('Final Written Warning',''));
insert into hr_tracker_records (kind,employee_code,employee_name,role_title,location,manager,event_date,event_date_raw,investigation_end,investigation_raw,findings,action_taken,bonus,filed_by,final_comments,source)
select 'disciplinary','B546','Danai Mkombo','NT','Plumstead','Isabelle Klusner',date '2026-04-20','20 April 26',date '2026-04-20','20 April 2026','First Written Warning','First Written Warning','50% Bonus','Sagaree','First Written Warning - RESIGNED','seed'
where not exists (select 1 from hr_tracker_records where kind='disciplinary' and employee_name='Danai Mkombo' and coalesce(event_date_raw,'')='20 April 26' and coalesce(action_taken,'')=coalesce('First Written Warning',''));
insert into hr_tracker_records (kind,employee_code,employee_name,role_title,location,manager,event_date,event_date_raw,investigation_end,investigation_raw,findings,action_taken,bonus,filed_by,final_comments,source)
select 'disciplinary','B608-M','Michaela Coleridge','ROM','BOA H/O','Management',date '2026-04-20','20 April 2026',date '2026-04-20','20 April 2026','Final Written Warning','Final Written Warning','No Bonus','Sagaree','Final Written Warning - RESIGNED','seed'
where not exists (select 1 from hr_tracker_records where kind='disciplinary' and employee_name='Michaela Coleridge' and coalesce(event_date_raw,'')='20 April 2026' and coalesce(action_taken,'')=coalesce('Final Written Warning',''));
insert into hr_tracker_records (kind,employee_code,employee_name,role_title,location,manager,event_date,event_date_raw,investigation_end,investigation_raw,findings,action_taken,bonus,filed_by,final_comments,source)
select 'disciplinary','B412','Zinzi Sam','NT','Rondebosch','Tabita',date '2026-04-20','20 April 2026',date '2026-04-20','20 April 2026','Final Written Warning','Final Written Warning','No Bonus','Sagaree','Final Written Warning','seed'
where not exists (select 1 from hr_tracker_records where kind='disciplinary' and employee_name='Zinzi Sam' and coalesce(event_date_raw,'')='20 April 2026' and coalesce(action_taken,'')=coalesce('Final Written Warning',''));
insert into hr_tracker_records (kind,employee_code,employee_name,role_title,location,manager,event_date,event_date_raw,investigation_end,investigation_raw,findings,action_taken,bonus,filed_by,final_comments,source)
select 'disciplinary','B389','Maryline Mugova','NT','Kloof','Shenaz Kavoshi',date '2026-04-20','20 April 2026',date '2026-04-20','20 April 2026','First Written Warning','First Written Warning','50% Bonus','Sagaree','First Written Warning','seed'
where not exists (select 1 from hr_tracker_records where kind='disciplinary' and employee_name='Maryline Mugova' and coalesce(event_date_raw,'')='20 April 2026' and coalesce(action_taken,'')=coalesce('First Written Warning',''));
insert into hr_tracker_records (kind,employee_code,employee_name,role_title,location,manager,event_date,event_date_raw,investigation_end,investigation_raw,findings,action_taken,bonus,filed_by,final_comments,source)
select 'disciplinary','B823-M','Noxolo Zikhali','AM','Eastgate','Nontethelelo Cebile Nxumalo',date '2026-04-20','20 April 2026',date '2026-04-20','20 April 2026','Final Written Warning','Final Written Warning','No Bonus','Sagaree','Final Written Warning - RESIGNED','seed'
where not exists (select 1 from hr_tracker_records where kind='disciplinary' and employee_name='Noxolo Zikhali' and coalesce(event_date_raw,'')='20 April 2026' and coalesce(action_taken,'')=coalesce('Final Written Warning',''));
insert into hr_tracker_records (kind,employee_code,employee_name,role_title,location,manager,event_date,event_date_raw,investigation_end,investigation_raw,findings,action_taken,bonus,filed_by,final_comments,source)
select 'disciplinary','B620-M','Mishca Johannes','AM','Sandown','Fahiema VD Schyff',date '2026-04-20','20 April 2026',date '2026-04-20','20 April 2026','Final Written Warning','Final Written Warning','No Bonus','Sagaree','Final Written Warning','seed'
where not exists (select 1 from hr_tracker_records where kind='disciplinary' and employee_name='Mishca Johannes' and coalesce(event_date_raw,'')='20 April 2026' and coalesce(action_taken,'')=coalesce('Final Written Warning',''));
insert into hr_tracker_records (kind,employee_code,employee_name,role_title,location,manager,event_date,event_date_raw,investigation_end,investigation_raw,findings,action_taken,bonus,filed_by,final_comments,source)
select 'disciplinary','B799','Learnmore Masona','NT','Cape Gate','Danel',date '2026-04-25','25 April 2026',date '2026-04-30','30 April 2026','First Written Warning','First Written Warning','50% Bonus','Sagaree','First Written Warning','seed'
where not exists (select 1 from hr_tracker_records where kind='disciplinary' and employee_name='Learnmore Masona' and coalesce(event_date_raw,'')='25 April 2026' and coalesce(action_taken,'')=coalesce('First Written Warning',''));
insert into hr_tracker_records (kind,employee_code,employee_name,role_title,location,manager,event_date,event_date_raw,investigation_end,investigation_raw,findings,action_taken,bonus,filed_by,final_comments,source)
select 'disciplinary','B457','Tyler-Jane Fynn','NT','Fourways','Andile Sisilana',date '2026-04-19','19 April 2026',date '2026-04-30','30 April 2026','First Written Warning','First Written Warning','50% Bonus','Sagaree','First Written Warning','seed'
where not exists (select 1 from hr_tracker_records where kind='disciplinary' and employee_name='Tyler-Jane Fynn' and coalesce(event_date_raw,'')='19 April 2026' and coalesce(action_taken,'')=coalesce('First Written Warning',''));
insert into hr_tracker_records (kind,employee_code,employee_name,role_title,location,manager,event_date,event_date_raw,investigation_end,investigation_raw,findings,action_taken,bonus,filed_by,final_comments,source)
select 'disciplinary','B457','Tyler-Jane Fynn','NT','Fourways','Andile Sisilana',date '2026-05-03','03 May 2026',date '2026-05-10','10 May 2026','Second Written Warning','Second Written Warning','50% Bonus','Sagaree','Second Written Warning','seed'
where not exists (select 1 from hr_tracker_records where kind='disciplinary' and employee_name='Tyler-Jane Fynn' and coalesce(event_date_raw,'')='03 May 2026' and coalesce(action_taken,'')=coalesce('Second Written Warning',''));
insert into hr_tracker_records (kind,employee_code,employee_name,role_title,location,manager,event_date,event_date_raw,investigation_end,investigation_raw,findings,action_taken,bonus,filed_by,final_comments,source)
select 'disciplinary','B457','Tyler-Jane Fynn','NT','Fourways','Andile Sisilana',date '2026-05-09','09 May 2026',date '2026-05-19','19 May 2026','Disciplinary Hearing TBS -Final Written Warning','Final Written Warning','No Bonus','Sagaree','Final Written Warning','seed'
where not exists (select 1 from hr_tracker_records where kind='disciplinary' and employee_name='Tyler-Jane Fynn' and coalesce(event_date_raw,'')='09 May 2026' and coalesce(action_taken,'')=coalesce('Final Written Warning',''));
insert into hr_tracker_records (kind,employee_code,employee_name,role_title,location,manager,event_date,event_date_raw,investigation_end,investigation_raw,findings,action_taken,bonus,filed_by,final_comments,source)
select 'disciplinary','B617','Nosipho Shangase','NT','Ballitto','Lindelwa ,,,,',date '2026-05-01','01 May 2026',date '2026-05-05','05 May 2026','First Written Warning','First Written Warning','50% Bonus','Sagaree','First Written Warning','seed'
where not exists (select 1 from hr_tracker_records where kind='disciplinary' and employee_name='Nosipho Shangase' and coalesce(event_date_raw,'')='01 May 2026' and coalesce(action_taken,'')=coalesce('First Written Warning',''));
insert into hr_tracker_records (kind,employee_code,employee_name,role_title,location,manager,event_date,event_date_raw,investigation_end,investigation_raw,findings,action_taken,bonus,filed_by,final_comments,source)
select 'disciplinary','B788','Shalom Gwiti','NT','Kuilsrivier','Jamie Naidoo',null,'04 May',date '2026-05-07','07 May 2026','First Written Warning','First Written Warning','50% Bonus','Sagaree','First Written Warning','seed'
where not exists (select 1 from hr_tracker_records where kind='disciplinary' and employee_name='Shalom Gwiti' and coalesce(event_date_raw,'')='04 May' and coalesce(action_taken,'')=coalesce('First Written Warning',''));
insert into hr_tracker_records (kind,employee_code,employee_name,role_title,location,manager,event_date,event_date_raw,investigation_end,investigation_raw,findings,action_taken,bonus,filed_by,final_comments,source)
select 'disciplinary','B789','Shalom Gwiti','NT','Kuilsrivier','Jamie Naidoo',null,'05 May',date '2026-05-08','08 May 2026','Second Written Warning',null,null,null,null,'seed'
where not exists (select 1 from hr_tracker_records where kind='disciplinary' and employee_name='Shalom Gwiti' and coalesce(event_date_raw,'')='05 May' and coalesce(action_taken,'')=coalesce(null,''));
insert into hr_tracker_records (kind,employee_code,employee_name,role_title,location,manager,event_date,event_date_raw,investigation_end,investigation_raw,findings,action_taken,bonus,filed_by,final_comments,source)
select 'disciplinary','B712','Boitumelo Mahlase','NT','MOS','Mbali Ndaba',null,'09 May',date '2026-05-09','09 May 2026','First Written Warning','First Written Warning','50% Bonus','Sagaree','First Written Warning','seed'
where not exists (select 1 from hr_tracker_records where kind='disciplinary' and employee_name='Boitumelo Mahlase' and coalesce(event_date_raw,'')='09 May' and coalesce(action_taken,'')=coalesce('First Written Warning',''));
insert into hr_tracker_records (kind,employee_code,employee_name,role_title,location,manager,event_date,event_date_raw,investigation_end,investigation_raw,findings,action_taken,bonus,filed_by,final_comments,source)
select 'disciplinary','B760-M','Sethu Njonga','AM','Westlake','HR',date '2026-05-08','8 May 2026',date '2026-05-10','10 May 2026','First Written Warning','First Written Warning','50% Bonus','Sagaree','First Written Warning','seed'
where not exists (select 1 from hr_tracker_records where kind='disciplinary' and employee_name='Sethu Njonga' and coalesce(event_date_raw,'')='8 May 2026' and coalesce(action_taken,'')=coalesce('First Written Warning',''));
insert into hr_tracker_records (kind,employee_code,employee_name,role_title,location,manager,event_date,event_date_raw,investigation_end,investigation_raw,findings,action_taken,bonus,filed_by,final_comments,source)
select 'disciplinary','B874','Ayanda Nkomo','NT','Eastgate','Elizabeth Malebane',date '2026-06-03','03 June 2026',date '2026-06-09','09 June 2026','First Written Warning','First Written Warning','50% Bonus','Sagaree','First Written Warning','seed'
where not exists (select 1 from hr_tracker_records where kind='disciplinary' and employee_name='Ayanda Nkomo' and coalesce(event_date_raw,'')='03 June 2026' and coalesce(action_taken,'')=coalesce('First Written Warning',''));
insert into hr_tracker_records (kind,employee_code,employee_name,role_title,location,manager,event_date,event_date_raw,investigation_end,investigation_raw,findings,action_taken,bonus,filed_by,final_comments,source)
select 'disciplinary','B874','Ayanda Nkomo','NT','Eastgate','Fazlen Mohammed',date '2026-05-22','22 May 2026',date '2026-05-03','03 May 2026','Final Written Warning','Final Written Warning','No Bonus','Sagaree','Final Written Warning','seed'
where not exists (select 1 from hr_tracker_records where kind='disciplinary' and employee_name='Ayanda Nkomo' and coalesce(event_date_raw,'')='22 May 2026' and coalesce(action_taken,'')=coalesce('Final Written Warning',''));
insert into hr_tracker_records (kind,employee_code,employee_name,role_title,location,manager,event_date,event_date_raw,investigation_end,investigation_raw,findings,action_taken,bonus,filed_by,final_comments,source)
select 'disciplinary','B408','Chiedza Matsheza','NT','Durbanville','Shameez Louw',date '2026-06-07','07 June 2026',date '2026-06-07','07 June 2026','First Written Warning','First Written Warning','50% Bonus','Sagaree','First Written Warning','seed'
where not exists (select 1 from hr_tracker_records where kind='disciplinary' and employee_name='Chiedza Matsheza' and coalesce(event_date_raw,'')='07 June 2026' and coalesce(action_taken,'')=coalesce('First Written Warning',''));
insert into hr_tracker_records (kind,employee_code,employee_name,role_title,location,manager,event_date,event_date_raw,investigation_end,investigation_raw,findings,action_taken,bonus,filed_by,final_comments,source)
select 'disciplinary','B411','Busiswa Sobani','NT','Seapoint','Anonymous',date '2026-06-09','09 June 2026',date '2026-06-09','09 June 2026','First Written Warning','First Written Warning','50% Bonus','Sagaree','First Written Warning','seed'
where not exists (select 1 from hr_tracker_records where kind='disciplinary' and employee_name='Busiswa Sobani' and coalesce(event_date_raw,'')='09 June 2026' and coalesce(action_taken,'')=coalesce('First Written Warning',''));
insert into hr_tracker_records (kind,employee_code,employee_name,role_title,location,manager,event_date,event_date_raw,investigation_end,investigation_raw,findings,action_taken,bonus,filed_by,final_comments,source)
select 'disciplinary','B710','Ayanda Bali','NT','MOS','Tshepiso',date '2026-06-10','10 June 2026',date '2026-06-22','22 June 2026','Disciplinary Hearing 22 June 2026','Final Written Warning','No Bonus','Sagaree','Final Written Warning','seed'
where not exists (select 1 from hr_tracker_records where kind='disciplinary' and employee_name='Ayanda Bali' and coalesce(event_date_raw,'')='10 June 2026' and coalesce(action_taken,'')=coalesce('Final Written Warning',''));
insert into hr_tracker_records (kind,employee_code,employee_name,role_title,location,manager,event_date,event_date_raw,investigation_end,investigation_raw,findings,action_taken,bonus,filed_by,final_comments,source)
select 'disciplinary','B430','Gisele Tshimbayi','NT','Durbanville RM','Chante Windsor',date '2026-06-05','05 June 2026',date '2026-06-04','04 June 2026','First Written Warning','First Written Warning','50% Bonus','Sagaree','First Written Warning','seed'
where not exists (select 1 from hr_tracker_records where kind='disciplinary' and employee_name='Gisele Tshimbayi' and coalesce(event_date_raw,'')='05 June 2026' and coalesce(action_taken,'')=coalesce('First Written Warning',''));
insert into hr_tracker_records (kind,employee_code,employee_name,role_title,location,manager,event_date,event_date_raw,investigation_end,investigation_raw,findings,action_taken,bonus,filed_by,final_comments,source)
select 'disciplinary','B408','Chiedza Matsheza','NT','Durbanville','Junia Jansen',date '2026-06-04','04 June 2026',date '2026-06-05','05 June 2026','Second Written Warning','Second Written Warning','50% Bonus','Sagaree','Second Written Warning','seed'
where not exists (select 1 from hr_tracker_records where kind='disciplinary' and employee_name='Chiedza Matsheza' and coalesce(event_date_raw,'')='04 June 2026' and coalesce(action_taken,'')=coalesce('Second Written Warning',''));
insert into hr_tracker_records (kind,employee_code,employee_name,role_title,location,manager,event_date,event_date_raw,investigation_end,investigation_raw,findings,action_taken,bonus,filed_by,final_comments,source)
select 'disciplinary','B307-M','Rene Brown','AM','Claremont','Isabelle Klusener',date '2026-06-08','08 June 2026',date '2026-06-09','09 June 2026','First Written Warning','First Written Warning','50% Bonus','Sagaree','First Written Warning','seed'
where not exists (select 1 from hr_tracker_records where kind='disciplinary' and employee_name='Rene Brown' and coalesce(event_date_raw,'')='08 June 2026' and coalesce(action_taken,'')=coalesce('First Written Warning',''));
insert into hr_tracker_records (kind,employee_code,employee_name,role_title,location,manager,event_date,event_date_raw,investigation_end,investigation_raw,findings,action_taken,bonus,filed_by,final_comments,source)
select 'disciplinary','B600-M','Charnelle Davids','AM','Claremont','Isabelle Klusener',date '2026-06-08','08 June 2026',date '2026-06-09','09 June 2026','First Written Warning','First Written Warning','50% Bonus','Sagaree','First Written Warning','seed'
where not exists (select 1 from hr_tracker_records where kind='disciplinary' and employee_name='Charnelle Davids' and coalesce(event_date_raw,'')='08 June 2026' and coalesce(action_taken,'')=coalesce('First Written Warning',''));
insert into hr_tracker_records (kind,employee_code,employee_name,role_title,location,manager,event_date,event_date_raw,investigation_end,investigation_raw,findings,action_taken,bonus,filed_by,final_comments,source)
select 'disciplinary','B866-M','Nonthombi Nombika','AM','Claremont','Isabelle Klusener',date '2026-06-08','08 June 2026',date '2026-06-09','09 June 2026','First Written Warning','First Written Warning','50% Bonus','Sagaree','First Written Warning','seed'
where not exists (select 1 from hr_tracker_records where kind='disciplinary' and employee_name='Nonthombi Nombika' and coalesce(event_date_raw,'')='08 June 2026' and coalesce(action_taken,'')=coalesce('First Written Warning',''));
insert into hr_tracker_records (kind,employee_code,employee_name,role_title,location,manager,event_date,event_date_raw,investigation_end,investigation_raw,findings,action_taken,bonus,filed_by,final_comments,source)
select 'disciplinary','B797-M','Yasmina Samsodien','AM','Claremont','Isabelle Klusener',date '2026-06-08','08 June 2026',date '2026-06-09','09 June 2026','First Written Warning','First Written Warning','50% Bonus','Sagaree','First Written Warning - RESIGNED','seed'
where not exists (select 1 from hr_tracker_records where kind='disciplinary' and employee_name='Yasmina Samsodien' and coalesce(event_date_raw,'')='08 June 2026' and coalesce(action_taken,'')=coalesce('First Written Warning',''));
insert into hr_tracker_records (kind,employee_code,employee_name,role_title,location,manager,event_date,event_date_raw,investigation_end,investigation_raw,findings,action_taken,bonus,filed_by,final_comments,source)
select 'disciplinary','B904','Fanele Mbokazi','NT','Ballito','Bongiwe Nxumalo',date '2026-06-10','10 June 2026',date '2026-06-10','10 June 2026','First Written Warning','First Written Warning','50% Bonus','Sagaree','First Written Warning','seed'
where not exists (select 1 from hr_tracker_records where kind='disciplinary' and employee_name='Fanele Mbokazi' and coalesce(event_date_raw,'')='10 June 2026' and coalesce(action_taken,'')=coalesce('First Written Warning',''));
insert into hr_tracker_records (kind,employee_code,employee_name,role_title,location,manager,event_date,event_date_raw,investigation_end,investigation_raw,findings,action_taken,bonus,filed_by,final_comments,source)
select 'disciplinary','B942','Thembeka Mbatha','NT','Ballito','Bongiwe Nxumalo',date '2026-06-10','10 June 2026',date '2026-06-10','10 June 2026','First Written Warning','First Written Warning','50% Bonus','Sagaree','First Written Warning','seed'
where not exists (select 1 from hr_tracker_records where kind='disciplinary' and employee_name='Thembeka Mbatha' and coalesce(event_date_raw,'')='10 June 2026' and coalesce(action_taken,'')=coalesce('First Written Warning',''));
insert into hr_tracker_records (kind,employee_code,employee_name,role_title,location,manager,event_date,event_date_raw,investigation_end,investigation_raw,findings,action_taken,bonus,filed_by,final_comments,source)
select 'disciplinary','B875','Mohau Mothepu','NT','Mushroom','Fazlen Mohammed',date '2026-06-06','6 June 2026',date '2026-06-10','10 June 2026','Disciplinary Hearing 22 June 2026','Final Written Warning','No Bonus','Sagaree','Final Written Warning','seed'
where not exists (select 1 from hr_tracker_records where kind='disciplinary' and employee_name='Mohau Mothepu' and coalesce(event_date_raw,'')='6 June 2026' and coalesce(action_taken,'')=coalesce('Final Written Warning',''));
insert into hr_tracker_records (kind,employee_code,employee_name,role_title,location,manager,event_date,event_date_raw,investigation_end,investigation_raw,findings,action_taken,bonus,filed_by,final_comments,source)
select 'disciplinary','B691','Ntombizanele Thawuse','NT','Claremont','AM',date '2026-06-12','12 June 2026',date '2026-06-16','16 June 2026','First Written Warning','First Written Warning','50% Bonus','Sagaree','First Written Warning','seed'
where not exists (select 1 from hr_tracker_records where kind='disciplinary' and employee_name='Ntombizanele Thawuse' and coalesce(event_date_raw,'')='12 June 2026' and coalesce(action_taken,'')=coalesce('First Written Warning',''));
insert into hr_tracker_records (kind,employee_code,employee_name,role_title,location,manager,event_date,event_date_raw,investigation_end,investigation_raw,findings,action_taken,bonus,filed_by,final_comments,source)
select 'disciplinary','B531','Delmah Mungwariri','NT','Cape Gate','Sinovuyo Rasi',date '2026-06-05','05 June 2026',date '2026-06-16','16 June 2026','First Written Warning','First Written Warning','50% Bonus','Sagaree','First Written Warning','seed'
where not exists (select 1 from hr_tracker_records where kind='disciplinary' and employee_name='Delmah Mungwariri' and coalesce(event_date_raw,'')='05 June 2026' and coalesce(action_taken,'')=coalesce('First Written Warning',''));
insert into hr_tracker_records (kind,employee_code,employee_name,role_title,location,manager,event_date,event_date_raw,investigation_end,investigation_raw,findings,action_taken,bonus,filed_by,final_comments,source)
select 'disciplinary','B192','Tatenda Tryphine Jena','NT','Sandown','Barbara Mateo',date '2026-06-13','13 June 2026',date '2026-06-13','13 June 2026','First Written Warning','First Written Warning','50% Bonus','Sagaree','First Written Warning','seed'
where not exists (select 1 from hr_tracker_records where kind='disciplinary' and employee_name='Tatenda Tryphine Jena' and coalesce(event_date_raw,'')='13 June 2026' and coalesce(action_taken,'')=coalesce('First Written Warning',''));
insert into hr_tracker_records (kind,employee_code,employee_name,role_title,location,manager,event_date,event_date_raw,investigation_end,investigation_raw,findings,action_taken,bonus,filed_by,final_comments,source)
select 'disciplinary','B640','Ruth Moto','NT','Sandown','Lungile Mtshali',date '2026-06-14','14 June 2026',date '2026-06-14','14 June 2026','First Written Warning','First Written Warning','50% Bonus','Sagaree','First Written Warning','seed'
where not exists (select 1 from hr_tracker_records where kind='disciplinary' and employee_name='Ruth Moto' and coalesce(event_date_raw,'')='14 June 2026' and coalesce(action_taken,'')=coalesce('First Written Warning',''));
insert into hr_tracker_records (kind,employee_code,employee_name,role_title,location,manager,event_date,event_date_raw,investigation_end,investigation_raw,findings,action_taken,bonus,filed_by,final_comments,source)
select 'disciplinary','B285','Veliswa Yalezo','NT','Tablebay','Chante Windsor',date '2026-06-18','18 June 2026',date '2026-06-18','18 June 2026','First Written Warning','First Written Warning','50% Bonus','Sagaree','First Written Warning','seed'
where not exists (select 1 from hr_tracker_records where kind='disciplinary' and employee_name='Veliswa Yalezo' and coalesce(event_date_raw,'')='18 June 2026' and coalesce(action_taken,'')=coalesce('First Written Warning',''));
insert into hr_tracker_records (kind,employee_code,employee_name,role_title,location,manager,event_date,event_date_raw,investigation_end,investigation_raw,findings,action_taken,bonus,filed_by,final_comments,source)
select 'disciplinary','B864-M','Charlene Grant','AM','Plumstead','Isabelle Klusener',date '2026-06-18','18 June 2026',date '2026-06-18','18 June 2026','Disciplinary Hearing - Terminated','Final Written Warning','No Bonus','Sagaree','Final Written Warning with Termination','seed'
where not exists (select 1 from hr_tracker_records where kind='disciplinary' and employee_name='Charlene Grant' and coalesce(event_date_raw,'')='18 June 2026' and coalesce(action_taken,'')=coalesce('Final Written Warning',''));
insert into hr_tracker_records (kind,employee_code,employee_name,role_title,location,manager,event_date,event_date_raw,investigation_end,investigation_raw,findings,action_taken,bonus,filed_by,final_comments,source)
select 'disciplinary','B902-M','Gakeema Kafaar','AM','Plumstead','Isabelle Klusener',date '2026-06-18','18 June 2026',date '2026-06-18','18 June 2026','First Written Warning','First Written Warning','50% Bonus','Sagaree','First Written Warning','seed'
where not exists (select 1 from hr_tracker_records where kind='disciplinary' and employee_name='Gakeema Kafaar' and coalesce(event_date_raw,'')='18 June 2026' and coalesce(action_taken,'')=coalesce('First Written Warning',''));
insert into hr_tracker_records (kind,employee_code,employee_name,role_title,location,manager,event_date,event_date_raw,investigation_end,investigation_raw,findings,action_taken,bonus,filed_by,final_comments,source)
select 'disciplinary','B865-M','Nicole Julius','AM','Riverlands','Isabelle Klusener',date '2026-06-11','11 June 2026',date '2026-06-22','22 June 2026','First Written Warning','First Written Warning','50% Bonus','Sagaree','First Written Warning','seed'
where not exists (select 1 from hr_tracker_records where kind='disciplinary' and employee_name='Nicole Julius' and coalesce(event_date_raw,'')='11 June 2026' and coalesce(action_taken,'')=coalesce('First Written Warning',''));
insert into hr_tracker_records (kind,employee_code,employee_name,role_title,location,manager,event_date,event_date_raw,investigation_end,investigation_raw,findings,action_taken,bonus,filed_by,final_comments,source)
select 'disciplinary','B787-M','Tarryn Arendse','AM','Riverlands','Isabelle Klusener',date '2026-06-11','11 June 2026',date '2026-06-22','22 June 2026','First Written Warning','First Written Warning','50% Bonus','Sagaree','First Written Warning','seed'
where not exists (select 1 from hr_tracker_records where kind='disciplinary' and employee_name='Tarryn Arendse' and coalesce(event_date_raw,'')='11 June 2026' and coalesce(action_taken,'')=coalesce('First Written Warning',''));
insert into hr_tracker_records (kind,employee_code,employee_name,role_title,location,manager,event_date,event_date_raw,investigation_end,investigation_raw,findings,action_taken,bonus,filed_by,final_comments,source)
select 'disciplinary','B663','Liskhanya Mazomba','NT','Kloof','Nazleen',date '2026-06-30','30 June 2026',date '2026-07-05','05 July 2026','First Written Warning','First Written Warning','50% Bonus','Sagaree','First Written Warning','seed'
where not exists (select 1 from hr_tracker_records where kind='disciplinary' and employee_name='Liskhanya Mazomba' and coalesce(event_date_raw,'')='30 June 2026' and coalesce(action_taken,'')=coalesce('First Written Warning',''));
insert into hr_tracker_records (kind,employee_code,employee_name,role_title,location,manager,event_date,event_date_raw,investigation_end,investigation_raw,findings,action_taken,bonus,filed_by,final_comments,source)
select 'disciplinary','B659','Vuyokazi Mjobo',null,null,null,date '2026-06-20','20 June 2026',null,null,null,null,null,null,null,'seed'
where not exists (select 1 from hr_tracker_records where kind='disciplinary' and employee_name='Vuyokazi Mjobo' and coalesce(event_date_raw,'')='20 June 2026' and coalesce(action_taken,'')=coalesce(null,''));
insert into hr_tracker_records (kind,employee_code,employee_name,role_title,location,manager,event_date,event_date_raw,investigation_end,investigation_raw,findings,action_taken,bonus,filed_by,final_comments,source)
select 'disciplinary','B116','Panayot Zinduwa','NT','Sandown','Anonymous',date '2026-07-01','01 July 2026',null,'03 July','Final Written Warning','Final Written Warning','No Bonus','Sagaree','Final Written Warning','seed'
where not exists (select 1 from hr_tracker_records where kind='disciplinary' and employee_name='Panayot Zinduwa' and coalesce(event_date_raw,'')='01 July 2026' and coalesce(action_taken,'')=coalesce('Final Written Warning',''));
insert into hr_tracker_records (kind,employee_code,employee_name,role_title,location,manager,event_date,event_date_raw,investigation_end,investigation_raw,findings,action_taken,bonus,filed_by,final_comments,source)
select 'disciplinary','B460','Ozlyn King','NT','Tablebay','H/O',date '2026-07-09','9 July 2026',date '2026-07-09','9 July 2026','Disciplinary Hearing - 09 July 2026','Terminated- Absconded','No Bonus','Sagaree','Terminated','seed'
where not exists (select 1 from hr_tracker_records where kind='disciplinary' and employee_name='Ozlyn King' and coalesce(event_date_raw,'')='9 July 2026' and coalesce(action_taken,'')=coalesce('Terminated- Absconded',''));
insert into hr_tracker_records (kind,employee_code,employee_name,role_title,location,manager,event_date,event_date_raw,investigation_end,investigation_raw,findings,action_taken,bonus,filed_by,final_comments,source)
select 'disciplinary',null,'Miche Cloete','AM','Riverlands','Nicole Julius',date '2026-07-03','03 July 2026',date '2026-07-09','09 July 2026','Disciplinary Hearing - 09 July 2027','Terminated- Gross Negligence','No Bonus','Sagaree','Terminated','seed'
where not exists (select 1 from hr_tracker_records where kind='disciplinary' and employee_name='Miche Cloete' and coalesce(event_date_raw,'')='03 July 2026' and coalesce(action_taken,'')=coalesce('Terminated- Gross Negligence',''));
insert into hr_tracker_records (kind,employee_code,employee_name,role_title,location,manager,event_date,event_date_raw,investigation_end,investigation_raw,findings,action_taken,bonus,filed_by,final_comments,source)
select 'disciplinary',null,'Boitumelo Mphake','AM','Fourways','Nazleen',date '2026-07-01','01 July 2026',date '2026-07-01','01 July 2026','First Written Warning','First Written Warning','50% Bonus','Sagaree','First Written Warning','seed'
where not exists (select 1 from hr_tracker_records where kind='disciplinary' and employee_name='Boitumelo Mphake' and coalesce(event_date_raw,'')='01 July 2026' and coalesce(action_taken,'')=coalesce('First Written Warning',''));
insert into hr_tracker_records (kind,employee_code,employee_name,role_title,location,manager,event_date,event_date_raw,investigation_end,investigation_raw,findings,action_taken,bonus,filed_by,final_comments,source)
select 'disciplinary','B509-CC','Nurzhaan De Klerk','CCSA','H/O','CEO',date '2026-08-11','11 August 2026',date '2026-08-11','11 August 2026','Disciplinary Hearing - First Written Warning','First Written Warning','No Bonus','Sagaree','First Written Warning','seed'
where not exists (select 1 from hr_tracker_records where kind='disciplinary' and employee_name='Nurzhaan De Klerk' and coalesce(event_date_raw,'')='11 August 2026' and coalesce(action_taken,'')=coalesce('First Written Warning',''));
insert into hr_tracker_records (kind,employee_code,employee_name,role_title,location,manager,event_date,event_date_raw,investigation_end,investigation_raw,findings,action_taken,bonus,filed_by,final_comments,source)
select 'disciplinary','B509-CC','Nurzhaan De Klerk','CCSA','H/O','CEO',date '2026-08-11','11 August 2026',date '2026-08-11','11 August 2026','Disciplinary Hearing - Final Written Warning','Final Written Warning','No Bonus','Sagaree','Final Written Warning','seed'
where not exists (select 1 from hr_tracker_records where kind='disciplinary' and employee_name='Nurzhaan De Klerk' and coalesce(event_date_raw,'')='11 August 2026' and coalesce(action_taken,'')=coalesce('Final Written Warning',''));
insert into hr_tracker_records (kind,employee_code,employee_name,role_title,location,manager,event_date,event_date_raw,investigation_end,investigation_raw,findings,action_taken,bonus,filed_by,final_comments,source)
select 'disciplinary','B686','Nolwazi Mthembu','CCA','H/O','Junia Jansen',date '2026-08-12','12 August 2026',date '2026-08-02','02 August 2026','First Written Warning','First Written Warning','50% Bonus','Sagaree','First Written Warning','seed'
where not exists (select 1 from hr_tracker_records where kind='disciplinary' and employee_name='Nolwazi Mthembu' and coalesce(event_date_raw,'')='12 August 2026' and coalesce(action_taken,'')=coalesce('First Written Warning',''));
insert into hr_tracker_records (kind,employee_code,employee_name,role_title,location,manager,event_date,event_date_raw,investigation_end,investigation_raw,findings,action_taken,bonus,filed_by,final_comments,source)
select 'disciplinary','B911-M','Shameez Louw','AM','Durbanville','Junia Jansen',date '2026-08-12','12 August 2026',date '2026-07-26','26 July 2026','First Written Warning','First Written Warning','50% Bonus','Sagaree','First Written Warning','seed'
where not exists (select 1 from hr_tracker_records where kind='disciplinary' and employee_name='Shameez Louw' and coalesce(event_date_raw,'')='12 August 2026' and coalesce(action_taken,'')=coalesce('First Written Warning',''));
insert into hr_tracker_records (kind,employee_code,employee_name,role_title,location,manager,event_date,event_date_raw,investigation_end,investigation_raw,findings,action_taken,bonus,filed_by,final_comments,source)
select 'disciplinary','B712','Boitumelo Mahlase','AM','MOS','Mbali Ndaba',date '2026-08-12','12 August 2026',date '2026-07-28','28 July 2026','First Written Warning','First Written Warning','50% Bonus','Sagaree','First Written Warning','seed'
where not exists (select 1 from hr_tracker_records where kind='disciplinary' and employee_name='Boitumelo Mahlase' and coalesce(event_date_raw,'')='12 August 2026' and coalesce(action_taken,'')=coalesce('First Written Warning',''));
insert into hr_tracker_records (kind,employee_code,employee_name,role_title,location,manager,event_date,event_date_raw,investigation_end,investigation_raw,findings,action_taken,bonus,filed_by,final_comments,source)
select 'disciplinary','B787-M','Tarryn Arendse','AM','Riverlands','Isabelle Klusner',date '2026-08-12','12 August 2026',date '2026-07-20','20 July 2026','First Written Warning','First Written Warning','No Bonus','Sagaree','First Written Warning','seed'
where not exists (select 1 from hr_tracker_records where kind='disciplinary' and employee_name='Tarryn Arendse' and coalesce(event_date_raw,'')='12 August 2026' and coalesce(action_taken,'')=coalesce('First Written Warning',''));
insert into hr_tracker_records (kind,employee_code,employee_name,role_title,location,manager,event_date,event_date_raw,investigation_end,investigation_raw,findings,action_taken,bonus,filed_by,final_comments,source)
select 'disciplinary','B787-M','Tarryn Arendse','AM','Riverlands','Isabelle Klusner',date '2026-08-12','12 August 2026',date '2026-08-12','12 August 2026','Second Written Warning','Second Written Warning','No Bonus','Sagaree','First Written Warning','seed'
where not exists (select 1 from hr_tracker_records where kind='disciplinary' and employee_name='Tarryn Arendse' and coalesce(event_date_raw,'')='12 August 2026' and coalesce(action_taken,'')=coalesce('Second Written Warning',''));
insert into hr_tracker_records (kind,employee_code,employee_name,role_title,location,manager,event_date,event_date_raw,investigation_end,investigation_raw,findings,action_taken,bonus,filed_by,final_comments,source)
select 'disciplinary','B105','Philiswa Mbambisa','NT','Bree','Nasreen Hassen - RM',date '2026-08-12','12 August 2026',date '2026-07-17','17 July 2026','First Written Warning','First Written Warning','50% Bonus','Sagaree','First Written Warning','seed'
where not exists (select 1 from hr_tracker_records where kind='disciplinary' and employee_name='Philiswa Mbambisa' and coalesce(event_date_raw,'')='12 August 2026' and coalesce(action_taken,'')=coalesce('First Written Warning',''));
insert into hr_tracker_records (kind,employee_code,employee_name,role_title,location,manager,event_date,event_date_raw,investigation_end,investigation_raw,findings,action_taken,bonus,filed_by,final_comments,source)
select 'disciplinary','B963','Akwando Zondo','NT','Plumstead','Fahiema VD Schyff',date '2026-08-12','12 August 2026',date '2026-08-12','12 August 2026','First Written Warning','First Written Warning','50% Bonus','Sagaree','First Written Warning','seed'
where not exists (select 1 from hr_tracker_records where kind='disciplinary' and employee_name='Akwando Zondo' and coalesce(event_date_raw,'')='12 August 2026' and coalesce(action_taken,'')=coalesce('First Written Warning',''));
insert into hr_tracker_records (kind,employee_code,employee_name,role_title,location,manager,event_date,event_date_raw,investigation_end,investigation_raw,findings,action_taken,bonus,filed_by,final_comments,source)
select 'disciplinary','B398-M','Danel Human','AM','Cape Gate','Chante Windsor - RM',date '2026-08-12','12 August 2026',date '2026-08-12','12 August 2026','First Written Warning','First Written Warning','50% Bonus','Sagaree','First Written Warning','seed'
where not exists (select 1 from hr_tracker_records where kind='disciplinary' and employee_name='Danel Human' and coalesce(event_date_raw,'')='12 August 2026' and coalesce(action_taken,'')=coalesce('First Written Warning',''));
insert into hr_tracker_records (kind,employee_code,employee_name,role_title,location,manager,event_date,event_date_raw,investigation_end,investigation_raw,findings,action_taken,bonus,filed_by,final_comments,source)
select 'disciplinary','B670','Elisfelo Magadzire','NT','Kuilsrivier','Jamie Nadoo',date '2026-08-12','12 August 2026',date '2026-08-24','24 August 2026','Meeting with HR - Second Written Warning','Second Written Warning','50% Bonus','Sagaree','Second Written Warning','seed'
where not exists (select 1 from hr_tracker_records where kind='disciplinary' and employee_name='Elisfelo Magadzire' and coalesce(event_date_raw,'')='12 August 2026' and coalesce(action_taken,'')=coalesce('Second Written Warning',''));
insert into hr_tracker_records (kind,employee_code,employee_name,role_title,location,manager,event_date,event_date_raw,investigation_end,investigation_raw,findings,action_taken,bonus,filed_by,final_comments,source)
select 'disciplinary','B923','Gugulethu Nxumalo','NT','Mall of The South','Tshepiso Sithole',date '2026-08-12','12 August 2026',date '2026-07-27','27 July 2026','First Written Warning','First Written Warning','50% Bonus','Sagaree','Second Written Warning','seed'
where not exists (select 1 from hr_tracker_records where kind='disciplinary' and employee_name='Gugulethu Nxumalo' and coalesce(event_date_raw,'')='12 August 2026' and coalesce(action_taken,'')=coalesce('First Written Warning',''));
insert into hr_tracker_records (kind,employee_code,employee_name,role_title,location,manager,event_date,event_date_raw,investigation_end,investigation_raw,findings,action_taken,bonus,filed_by,final_comments,source)
select 'disciplinary','B1005','Lydia Makhubela','NT','Mushroom Farm','Mbali Ndaba',date '2026-08-14','14 August 2026',date '2026-08-14','14 August 2026','First Written Warning','First Written Warning','50% Bonus','Sagaree','First Written Warning','seed'
where not exists (select 1 from hr_tracker_records where kind='disciplinary' and employee_name='Lydia Makhubela' and coalesce(event_date_raw,'')='14 August 2026' and coalesce(action_taken,'')=coalesce('First Written Warning',''));
insert into hr_tracker_records (kind,employee_code,employee_name,role_title,location,manager,event_date,event_date_raw,investigation_end,investigation_raw,findings,action_taken,bonus,filed_by,final_comments,source)
select 'disciplinary','B1002','Mbali Ntuli','NT','Mushroom Farm','Mbali Ndaba',date '2026-08-14','14 August 2026',date '2026-08-14','14 August 2026','First Written Warning','First Written Warning','50% Bonus','Sagaree','First Written Warning','seed'
where not exists (select 1 from hr_tracker_records where kind='disciplinary' and employee_name='Mbali Ntuli' and coalesce(event_date_raw,'')='14 August 2026' and coalesce(action_taken,'')=coalesce('First Written Warning',''));
insert into hr_tracker_records (kind,employee_code,employee_name,role_title,location,manager,event_date,event_date_raw,investigation_end,investigation_raw,findings,action_taken,bonus,filed_by,final_comments,source)
select 'disciplinary','B852','Dimakatso Marako','NT','Mushroom Farm','Mbali Ndaba',date '2026-08-14','14 August 2026',date '2026-08-14','14 August 2026','First Written Warning','First Written Warning','50% Bonus','Sagaree','First Written Warning','seed'
where not exists (select 1 from hr_tracker_records where kind='disciplinary' and employee_name='Dimakatso Marako' and coalesce(event_date_raw,'')='14 August 2026' and coalesce(action_taken,'')=coalesce('First Written Warning',''));
insert into hr_tracker_records (kind,employee_code,employee_name,role_title,location,manager,event_date,event_date_raw,investigation_end,investigation_raw,findings,action_taken,bonus,filed_by,final_comments,source)
select 'disciplinary','B816','Sthembile Ndlovu','NT','Mushroom Farm','Mbali Ndaba',date '2026-08-14','14 August 2026',date '2026-08-14','14 August 2026','First Written Warning','First Written Warning','50% Bonus','Sagaree','First Written Warning','seed'
where not exists (select 1 from hr_tracker_records where kind='disciplinary' and employee_name='Sthembile Ndlovu' and coalesce(event_date_raw,'')='14 August 2026' and coalesce(action_taken,'')=coalesce('First Written Warning',''));
insert into hr_tracker_records (kind,employee_code,employee_name,role_title,location,manager,event_date,event_date_raw,investigation_end,investigation_raw,findings,action_taken,bonus,filed_by,final_comments,source)
select 'disciplinary','B845','Lebohang Moloto','NT','MOS','Tshepiso Sithole',date '2026-08-14','14 August 2026',date '2026-07-27','27 July 2026','First Written Warning','First Written Warning','50% Bonus','Sagaree','First Written Warning','seed'
where not exists (select 1 from hr_tracker_records where kind='disciplinary' and employee_name='Lebohang Moloto' and coalesce(event_date_raw,'')='14 August 2026' and coalesce(action_taken,'')=coalesce('First Written Warning',''));
insert into hr_tracker_records (kind,employee_code,employee_name,role_title,location,manager,event_date,event_date_raw,investigation_end,investigation_raw,findings,action_taken,bonus,filed_by,final_comments,source)
select 'disciplinary','B562-M','Linda Dosi','AM','Rondebosch','Isabelle Klusner',date '2026-08-19','19 August 2026',date '2026-07-17','17 July 2026','Disicplinary Hearing - 19 August 2026 Final Written Warning','Final Written Warning','No Bonus','Sagaree','Final Written Warning - RESIGNED','seed'
where not exists (select 1 from hr_tracker_records where kind='disciplinary' and employee_name='Linda Dosi' and coalesce(event_date_raw,'')='19 August 2026' and coalesce(action_taken,'')=coalesce('Final Written Warning',''));
insert into hr_tracker_records (kind,employee_code,employee_name,role_title,location,manager,event_date,event_date_raw,investigation_end,investigation_raw,findings,action_taken,bonus,filed_by,final_comments,source)
select 'disciplinary','B974','Sivashney Williams','NT','Winelands','Chante Windsor',date '2026-08-19','19 August 2026',date '2026-07-17','17 July 2026','Disicplinary Hearing - 19 August 2026 Terminated','Terminated','No Bonus','Sagaree','Terminated','seed'
where not exists (select 1 from hr_tracker_records where kind='disciplinary' and employee_name='Sivashney Williams' and coalesce(event_date_raw,'')='19 August 2026' and coalesce(action_taken,'')=coalesce('Terminated',''));
insert into hr_tracker_records (kind,employee_code,employee_name,role_title,location,manager,event_date,event_date_raw,investigation_end,investigation_raw,findings,action_taken,bonus,filed_by,final_comments,source)
select 'disciplinary','B499','Caitlin Theunissen','NT','Durbanville','Chante Windsor',date '2026-08-19','19 August 2026',date '2026-07-17','17 July 2026','Disicplinary Hearing - 19 August 2026 Terminated','Terminated','No Bonus','Sagaree','Terminated','seed'
where not exists (select 1 from hr_tracker_records where kind='disciplinary' and employee_name='Caitlin Theunissen' and coalesce(event_date_raw,'')='19 August 2026' and coalesce(action_taken,'')=coalesce('Terminated',''));
